server.port=8080
spring.application.name=vote-initiation

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=36kashili@gmail.com
spring.mail.password=edjq qjmr cpjt zxqf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# CORS
app.cors.allowed-origins=http://localhost:5173
